# strings.py

STRINGS = {
    "en": {
        "welcome": "👋 *Welcome to Student Match Bot!*\n\nI help you find peers based on skills and interests.",
        "lang_select": "Please select your language / Пожалуйста, выберите язык:",
        "start_wizard": "📝 Create Profile",
        "find_matches": "🎯 Find Matches",
        "view_rules": "📜 View Rules",
        "help": "❓ Help",
        "profile_exists": "You already have a profile! Use /myprofile to view it or /edit to update it.",
        "ask_university": "Let's create your profile! First, what is your university name?",
        "ask_year": "🏛 *{uni}* - Excellent choice!\n\nWhat year or course are you in? (Select below or type it)",
        "ask_skills": "🎓 *Level:* {year}\n\nNow, tell me your top skills (comma-separated).\nExample: Python, Research, Design",
        "ask_interests": "💡 Great! Now, tell me your top skills (comma-separated).\nExample: Python, Public Speaking, UI Design", # This looks like a copy-paste error in original code, I'll fix it here
        "ask_interests_real": "🌟 Nice! What are your current interests? (comma-separated)\nExample: AI, Startups, Hiking, Music",
        "ask_goals": "🎯 Almost there! What is your main goal right now?\nExample: Finding a co-founder, internship help, or just networking.",
        "profile_updated": "Success! Your profile has been updated.\nUse /myprofile to see how it looks or /matches to find peers!",
        "cancel": "❌ Cancel",
        "wizard_cancelled": "❌ Profile creation cancelled. Use /profile to start again.",
        "my_profile_title": "👤 *Your Profile*",
        "uni": "🏛 *University:*",
        "year": "📅 *Year/Course:*",
        "skills": "🛠 *Skills:*",
        "interests": "🌟 *Interests:*",
        "goals": "🎯 *Goals:*",
        "edit_profile": "✏️ Edit Profile",
        "no_profile": "📭 You haven't created a profile yet! Use /profile to start.",
        "edit_menu_title": "⚙️ *Edit Menu*\nWhat would you like to update?",
        "edit_uni": "🏛 University",
        "edit_year": "🎓 Year/Course",
        "edit_skills": "🛠 Skills",
        "edit_interests": "🌟 Interests",
        "edit_goals": "🎯 Goals",
        "restart_wizard": "🔄 Restart Wizard",
        "delete_profile": "🗑 Delete Profile",
        "done": "✅ Done",
        "confirm_delete": "🚨 *Warning*: Profile deletion cannot be undone. All your data and match history will be removed.\n\nAre you sure?",
        "yes_delete": "⚠️ YES, Delete Everything",
        "no_keep": "❌ No, Keep My Profile",
        "profile_deleted": "🗑 *Your profile has been deleted.*\n\nYou can always create a new one using /profile.",
        "enter_uni": "🏦 Enter your new university name:",
        "enter_year": "🎓 Enter your new year/course:",
        "enter_skills": "🛠 Enter your new skills (separated by commas):",
        "enter_interests": "🌟 Enter your new interests (separated by commas):",
        "enter_goals": "🎯 Enter your new primary goal:",
        "matches_found": "🎯 *Found {count} matches for you:*",
        "no_matches": "No matching found yet. Try updating your profile or check back later!",
        "match_reason_uni": "you both study at {uni}",
        "match_reason_skills": "you both know {skills}",
        "match_reason_interests": "you are both interested in {interests}",
        "match_reason_default": "your goals and interests align well",
        "report_user": "🚩 Report User",
        "user_reported": "User reported. Thank you for keeping our community safe!",
        "lang_changed": "Language changed to English! 🇺🇸",
    },
    "ru": {
        "welcome": "👋 *Добро пожаловать в Student Match Bot!*\n\nЯ помогу вам найти единомышленников на основе ваших навыков и интересов.",
        "lang_select": "Пожалуйста, выберете язык / Please select your language:",
        "start_wizard": "📝 Создать профиль",
        "find_matches": "🎯 Найти пары",
        "view_rules": "📜 Правила",
        "help": "❓ Помощь",
        "profile_exists": "У вас уже есть профиль! Используйте /myprofile для просмотра или /edit для обновления.",
        "ask_university": "Давайте создадим ваш профиль! Во-первых, как называется ваш университет?",
        "ask_year": "🏛 *{uni}* - Отличный выбор!\n\nНа каком вы курсе? (Выберите ниже или введите вручную)",
        "ask_skills": "🎓 *Уровень:* {year}\n\nТеперь расскажите о своих основных навыках (через запятую).\nПример: Python, Исследования, Дизайн",
        "ask_interests_real": "🌟 Отлично! Какие у вас интересы? (через запятую)\nПример: ИИ, Стартапы, Походы, Музыка",
        "ask_goals": "🎯 И последнее! Какая у вас основная цель сейчас?\nПример: Поиск сооснователя, помощь в стажировке или просто нетворкинг.",
        "profile_updated": "Успех! Ваш профиль обновлен.\nИспользуйте /myprofile или /matches, чтобы найти коллег!",
        "cancel": "❌ Отмена",
        "wizard_cancelled": "❌ Создание профиля отменено. Используйте /profile, чтобы начать заново.",
        "my_profile_title": "👤 *Ваш профиль*",
        "uni": "🏛 *Университет:*",
        "year": "📅 *Курс:*",
        "skills": "🛠 *Навыки:*",
        "interests": "🌟 *Интересы:*",
        "goals": "🎯 *Цели:*",
        "edit_profile": "✏️ Редактировать",
        "no_profile": "📭 Вы еще не создали профиль! Используйте /profile для начала.",
        "edit_menu_title": "⚙️ *Меню редактирования*\nЧто вы хотите обновить?",
        "edit_uni": "🏛 Университет",
        "edit_year": "🎓 Курс",
        "edit_skills": "🛠 Навыки",
        "edit_interests": "🌟 Интересы",
        "edit_goals": "🎯 Цели",
        "restart_wizard": "🔄 Перезапустить визард",
        "delete_profile": "🗑 Удалить профиль",
        "done": "✅ Готово",
        "confirm_delete": "🚨 *Внимание*: Удаление профиля нельзя отменить. Все ваши данные и история совпадений будут удалены.\n\nВы уверены?",
        "yes_delete": "⚠️ ДА, удалить всё",
        "no_keep": "❌ Нет, оставить профиль",
        "profile_deleted": "🗑 *Ваш профиль был удален.*\n\nВы всегда можете создать новый с помощью /profile.",
        "enter_uni": "🏦 Введите новое название университета:",
        "enter_year": "🎓 Введите ваш курс:",
        "enter_skills": "🛠 Введите новые навыки (через запятую):",
        "enter_interests": "🌟 Введите новые интересы (через запятую):",
        "enter_goals": "🎯 Введите вашу новую основную цель:",
        "matches_found": "🎯 *Найдено {count} совпадений:*",
        "no_matches": "Совпадений пока нет. Попробуйте обновить профиль позже!",
        "match_reason_uni": "вы оба учитесь в {uni}",
        "match_reason_skills": "вы оба знаете {skills}",
        "match_reason_interests": "вы оба интересуетесь {interests}",
        "match_reason_default": "ваши цели и интересы хорошо совпадают",
        "report_user": "🚩 Пожаловаться",
        "user_reported": "Пользователь зарепорчен. Спасибо за помощь в безопасности сообщества!",
        "lang_changed": "Язык изменен на Русский! 🇷🇺",
    }
}
